import { describe, expect, it } from 'vitest';
import { course } from './course';
import { lessonOrder } from './lesson-order';

describe('lesson-order', () => {
	// lesson-order.ts is generated by `bun run lint:content`. If someone adds a
	// lesson to course.ts and skips that step, unlock order silently ignores the
	// new lesson — this is the check that catches it.
	it('matches the lesson order in course.ts', () => {
		const fromCourse = course.flatMap((u) => u.lessons.map((l) => l.id));
		expect([...lessonOrder]).toEqual(fromCourse);
	});

	it('has no duplicate ids', () => {
		expect(new Set(lessonOrder).size).toBe(lessonOrder.length);
	});
});
