import { describe, expect, it } from 'vitest';
import { course } from './course';
import { lessonOrder, optionalLessons } from './lesson-order';

describe('lesson-order', () => {
	// lesson-order.ts is generated by `bun run lint:content`. If someone adds a
	// lesson to course.ts and skips that step, unlock order silently ignores the
	// new lesson — this is the check that catches it.
	it('matches the lesson order in course.ts', () => {
		const fromCourse = course.flatMap((u) => u.lessons.map((l) => l.id));
		expect([...lessonOrder]).toEqual(fromCourse);
	});

	it('has no duplicate ids', () => {
		expect(new Set(lessonOrder).size).toBe(lessonOrder.length);
	});

	it('matches the optional lessons in course.ts', () => {
		const fromCourse = course.flatMap((u) => u.lessons.filter((l) => l.optional).map((l) => l.id));
		expect([...optionalLessons]).toEqual(fromCourse);
	});

	// An optional lesson that isn't in the order would be invisible to
	// progress entirely — it is left off the ladder, not out of the course.
	it('keeps every optional lesson in the unlock order', () => {
		for (const id of optionalLessons) expect(lessonOrder).toContain(id);
	});

	// The last lesson gates nothing, so making it optional would be a no-op
	// that reads like a decision. More importantly, a run of optional lessons
	// at the end would leave `currentLesson` undefined while the path still
	// shows unfinished nodes.
	it('never makes the final lesson optional', () => {
		expect(optionalLessons).not.toContain(lessonOrder[lessonOrder.length - 1]);
	});
});
