// GENERATED by `bun run lint:content` — do not edit by hand.
//
// The flat unlock order, split out of course.ts so progress.svelte.ts (which
// the root layout pulls in on every page) does not drag all ~2000 lines of
// exercise content along with it. course.ts stays the source of truth;
// lesson-order.test.ts fails if this file drifts from it.
export const lessonOrder: readonly string[] = [
	"first-words",
	"how-are-you",
	"polite-talk",
	"one-to-five",
	"six-to-ten",
	"burmese-digits",
	"ka-row",
	"sa-row",
	"ta-pa-rows",
	"tea-shop",
	"yummy",
	"ordering",
	"my-family",
	"siblings",
	"kids-and-love",
	"around-town",
	"where-is-it",
	"left-and-right",
	"today-tomorrow",
	"morning-to-night",
	"days-of-week"
];
